version: '3.8'

services:
  app:
    build: .
    container_name: ale-song-list
    restart: unless-stopped
    ports:
      - "45100:3000"
    environment:
      - NODE_ENV=production
      - ADMIN_SECRET_KEY=admin123  # 请修改密钥
    volumes:
      - ./data:/app/backend/data
      - ./uploads:/app/frontend/uploads
      - ./logs:/app/backend/logs
