version: '3.8'

services:
  app:
    image: ghcr.io/funx2ysam/ale-song-list:latest
    container_name: ale-song-list
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ADMIN_SECRET_KEY=admin123  # 请修改密钥
      # 站点设置 (可选，自定义默认站点配置)
      - SITE_TITLE=${SITE_TITLE:-歌单系统}
      - SITE_FAVICON=${SITE_FAVICON:-}
      - ADMIN_TITLE_SUFFIX=${ADMIN_TITLE_SUFFIX:- - 管理后台}
      # OCR服务配置 (可选，如需启用图片识别功能请配置)
      - ALIYUN_ACCESS_KEY_ID=${ALIYUN_ACCESS_KEY_ID:-}
      - ALIYUN_ACCESS_KEY_SECRET=${ALIYUN_ACCESS_KEY_SECRET:-}
      - ALIYUN_OCR_ENDPOINT=${ALIYUN_OCR_ENDPOINT:-ocr-api.cn-hangzhou.aliyuncs.com}
    volumes:
      - ./data:/app/backend/data
      - ./uploads:/app/frontend/uploads
      - ./logs:/app/backend/logs 